// apps/mfe-react/src/registry.tsx
import type { ReactNode } from 'react';
import Weather from './features/weather/Weather';

// Registry of components hosted by this React micro-frontend.
// Add an entry here to surface a new component in the nav + home grid.
export interface ComponentEntry {
  path: string;
  label: string;
  description: string;
  emoji: string;
  element: ReactNode;
}

export const COMPONENTS: ComponentEntry[] = [
  {
    path: '/weather',
    label: 'Weather',
    description: 'Live 7-day forecast from the Open-Meteo API.',
    emoji: '⛅',
    element: <Weather />,
  },
];

// apps/mfe-angular/src/app/registry.ts
import type { Type } from '@angular/core';

// Registry of components hosted by this Angular micro-frontend.
// Add an entry here to surface a new component in the nav + home grid + routes.
export interface MfeComponent {
  path: string;
  label: string;
  description: string;
  emoji: string;
  loadComponent: () => Promise<Type<unknown>>;
}

export const COMPONENTS: MfeComponent[] = [
  {
    path: 'wordle',
    label: 'Wordle',
    description: 'Daily word game, word of the day served from Supabase.',
    emoji: '🟩',
    loadComponent: () => import('./wordle/wordle').then((m) => m.Wordle),
  },
];
