// apps/mfe-angular/src/app/app.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { COMPONENTS } from './registry';

// This micro-frontend is a self-contained mini-app: its own router and many
// components under one remote. The shell embeds the whole app via iframe.
@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="min-h-full w-full bg-slate-50">
      <header class="border-b border-slate-200 bg-white">
        <div class="mx-auto flex max-w-2xl flex-wrap items-center gap-2 px-4 py-3">
          <span
            class="mr-1 rounded-full bg-rose-100 px-2.5 py-0.5 text-xs font-semibold text-rose-700"
          >
            Angular MFE
          </span>
          <nav class="flex flex-wrap items-center gap-1">
            <a
              routerLink="/"
              routerLinkActive="!bg-slate-900 !text-white"
              [routerLinkActiveOptions]="{ exact: true }"
              class="rounded-lg px-3 py-1.5 text-sm font-medium text-slate-600 transition hover:bg-slate-100 hover:text-slate-900"
            >
              Home
            </a>
            @for (c of components; track c.path) {
              <a
                [routerLink]="c.path"
                routerLinkActive="!bg-slate-900 !text-white"
                class="rounded-lg px-3 py-1.5 text-sm font-medium text-slate-600 transition hover:bg-slate-100 hover:text-slate-900"
              >
                {{ c.label }}
              </a>
            }
          </nav>
        </div>
      </header>
      <main class="py-2">
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
})
export class App {
  readonly components = COMPONENTS;
}

// apps/shell/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';

const links = [
  { to: '/', label: 'Home' },
  { to: '/react', label: 'React' },
  { to: '/angular', label: 'Angular' },
  { to: '/how-its-built', label: 'How it’s built' },
];
</script>

<template>
  <div class="min-h-screen bg-slate-50 text-slate-900">
    <header class="sticky top-0 z-10 border-b border-slate-200 bg-white/80 backdrop-blur">
      <div class="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
        <RouterLink to="/" class="flex items-center gap-2">
          <span
            class="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-sm font-bold text-white"
          >
            k
          </span>
          <span class="font-semibold tracking-tight">kobi<span class="text-slate-400">.ai</span></span>
        </RouterLink>
        <nav class="flex items-center gap-1">
          <RouterLink
            v-for="link in links"
            :key="link.to"
            :to="link.to"
            class="rounded-lg px-3 py-1.5 text-sm font-medium text-slate-600 transition hover:bg-slate-100 hover:text-slate-900"
            active-class="!bg-slate-900 !text-white"
            exact-active-class="!bg-slate-900 !text-white"
          >
            {{ link.label }}
          </RouterLink>
        </nav>
      </div>
    </header>

    <main class="mx-auto max-w-5xl px-4 py-8">
      <RouterView />
    </main>

    <footer class="mx-auto max-w-5xl px-4 py-8 text-center text-xs text-slate-400">
      Vue shell · React &amp; Angular micro-frontends · Supabase backend
    </footer>
  </div>
</template>
